
services:
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "7005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  paymentservice:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    ports:
      - "7262:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  notificationservice:
    build:
      context: .
      dockerfile: NotificationService/Dockerfile
    ports:
      - "7002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development